### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by aimengaba** [kazijehangir/BloodHub#11]

**Comment by kazijehangir** [comment]
Is it fixed?

**Comment by kazijehangir** [comment]
Fixed back button crash. https://github.com/kazijehangir/BloodHub/commit/405603cb69a053e5e0a73e01cbfceb4e73c43b7c
Forgot password functionality works.
![screenshot_gmail_20180322-183214](https://user-images.githubusercontent.com/12759818/37773470-86fe9870-2dff-11e8-8417-5e85624a5353.png)
