### ISSUE TITLE
Request name labels invisible with long name

### ISSUE THREAD

**Issue by kazijehangir** [kazijehangir/BloodHub#33]
If the name/location text is too long the label gets hidden by the text.

**Comment by kazijehangir** [comment]
![screenshot_bloodhub_20180320-144940](https://user-images.githubusercontent.com/12759818/37647498-36524276-2c4e-11e8-9ed1-54b6b115f68d.png)
![screenshot_bloodhub_20180320-144935](https://user-images.githubusercontent.com/12759818/37647499-368b6088-2c4e-11e8-9342-6d46173b8e8b.png)

**Comment by mahnoormmalik** [comment]
![screenshot_20180320-215146](https://user-images.githubusercontent.com/19840103/37669591-0cd690a6-2c89-11e8-8ce6-d8ecd944e1d6.png)

Fixed it by settingsetting max height. Let me know if this looks fine so I can change it in the rest of card views

**Comment by mahnoormmalik** [comment]
![screenshot_20180320-215352](https://user-images.githubusercontent.com/19840103/37669682-4c7c597a-2c89-11e8-9424-e3654e1af7d1.png)
Request detail view

**Comment by kazijehangir** [comment]
The request detail view looks good. The requests list is the same no?

**Comment by kazijehangir** [comment]
Nevermind. Got it. You removed the Name: part from every card and made the name bold. Looks good.

**Comment by mahnoormmalik** [comment]
Yes and only the first two lines are visible in the name and location label. I'll change rest of the card views too

**Comment by kazijehangir** [comment]
Okay thanks. Mark this closed when its done.
