### ISSUE TITLE
Users should not be able to accept requests they submitted

### ISSUE THREAD

**Issue by mahnoormmalik** [kazijehangir/BloodHub#38]
Either we don't show the requests submitted by the user in the home requests fragment or have a way to identify that a particular request was submitted by them which has no donate button.

**Comment by kazijehangir** [comment]
![screenshot_bloodhub_20180401-212154](https://user-images.githubusercontent.com/12759818/38175239-c8471a50-35f2-11e8-99a6-b01c36a9ddb5.png)
Changed the request details page to take care of this. Do you think we need some indication in the request list page too?

**Comment by kazijehangir** [comment]
@mahnoormmalik Please review.

**Comment by mahnoormmalik** [comment]
I think this is fine for now
